### ISSUE TITLE
verify two strings previously considered illegal

### ISSUE THREAD

**Issue by wkliao** [JuliaLang/utf8proc#115]
When using utf8proc version 1.1.1, the following two strings are considered illegal.
"x\xEF\xBF\xBE"
"x\xEF\xBF\xBF"

But they seem to become legal in latest release version 2.1.0.
I just want to make sure this behavior in 2.1.0 is correct, not an error.

[NetCDF](https://github.com/Unidata/netcdf-c) was recently updated to use utf8proc 2.1.0 and one of its test program fails on these two strings (still considers them illegal). Please confirm this new behavior, so we can adjust NetCDF and [PnetCDF](https://github.com/Parallel-NetCDF/PnetCDF) accordingly. Thanks.

CC: NetCDF developers @DennisHeimbigner @WardF

**Comment by stevengj** [comment]
Yes, the current behavior is correct and the previous behavior was a bug (#34).  The two strings you mention contain Unicode "noncharacters" ([U+FFFE](http://www.fileformat.info/info/unicode/char/fffe/index.htm) and [U+FFFF](http://www.fileformat.info/info/unicode/char/ffff/index.htm)), which are valid in Unicode strings.

(It is clearer to say "invalid" rather than "illegal" for this kind of thing, by the way.  Violating the Unicode standard does not make you a criminal, last I checked :wink:!)
